data:
  train_files: ["data/processed/synthetic_regular_processed.txt"]
  val_files: null
  test_files: null
  batch_size: 256
  num_workers: 12
  cache_dir: ".cache/"
  cache_format: "npz"
  max_length: 512
  val_split: 0.05
  test_split: 0
modeling_config:
  architecture:
    name: "transformer_encoder"
    d_model: 256
    nhead: 4
    num_encoder_layers: 4
    dim_feedforward: 1024
    dropout: 0.1

  optimizer:
    name: "adamw"
    lr: 1e-4
    weight_decay: 0.01
    betas: [0.9, 0.98]

  scheduler: 
    name: "linear_warmup"
    warmup_ratio: 0.1
